version: '2'
services:
  reverifi:
    container_name: reverifi
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - PORT=80
      - VIRTUAL_HOST=reverifi.docker
      - REACT_APP_API_URL=http://localhost:61435
    volumes:
      - ${PWD}:/app
    ports:
      - 3000:80
    command: ['/bin/boot.sh']
