export const weekDays = [
  {
    available: true,
    label: 'Sunday',
    name: 'Sun',
    number: 0,
    outOfDate: false,
    time: { end: null, start: null },
  },
  {
    available: true,
    label: 'Monday',
    name: 'Mon',
    number: 1,
    outOfDate: false,
    time: { end: null, start: null },
  },
  {
    available: true,
    label: 'Tuesday',
    name: 'Tue',
    number: 2,
    outOfDate: false,
    time: { end: null, start: null },
  },
  {
    available: true,
    label: 'Wednesday',
    name: 'Wed',
    number: 3,
    outOfDate: false,
    time: { end: null, start: null },
  },
  {
    available: true,
    label: 'Thursday',
    name: 'Thu',
    number: 4,
    outOfDate: false,
    time: { end: null, start: null },
  },
  {
    available: true,
    label: 'Friday',
    name: 'Fri',
    number: 5,
    outOfDate: false,
    time: { end: null, start: null },
  },
  {
    available: true,
    label: 'Saturday',
    name: 'Sat',
    number: 6,
    outOfDate: false,
    time: { end: null, start: null },
  },
];
export default weekDays;
