on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: reverifi-frontend
          key: ${{ secrets.FRONT_END_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm && source ~/.nvm/nvm.sh
            export REACT_APP_API_URL=https://reverifi.sociumtech.com
            cd /home/reverifi-frontend/reverifi && git checkout package-lock.json && git pull origin main
            cd /home/reverifi-frontend/reverifi
            /usr/bin/rm -rf node_modules
            /usr/bin/npm install && npm cache clean --force
            /usr/bin/npm cache verify
            /usr/bin/npm run build
